config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resources :users, only: [:new, :create, :show] do
    resources :ideas, except: [:index]
  end

  resources :ideas, only: [:index, :show]

  namespace :admin do
    resources :categories
    resources :images, only: [:index, :create, :new, :destroy, :show]
  end

  resources :categories, only: [:index, :show]

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates_uniqueness_of :name
  has_many :ideas, dependent: :destroy
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates_presence_of :body, :title
  belongs_to :category
  belongs_to :user
  has_many :idea_images, dependent: :destroy
  has_many :images, through: :idea_images

  def set_images(params)
    unless params.nil?
      images << params.map { |i| Image.find(i) }
    end
  end

end

app/models/idea_image.rb
class IdeaImage < ApplicationRecord
  belongs_to :image, optional: true
  belongs_to :idea, optional: true 
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :idea_images
  has_many :ideas, through: :idea_images

end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :username, :email, :password_digest
  validates_uniqueness_of :username, :email
  has_many :ideas, dependent: :destroy
  has_secure_password

  enum role: ['default', 'admin']
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  private

    def require_admin
      render file: "/public/404" unless current_admin?
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:destroy, :show, :edit, :update]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_category_path(@category)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @category.update!(category_params)
    redirect_to admin_category_path(@category)
  end

  def destroy
    @category.destroy!
    redirect_to admin_categories_path
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end

    def set_category
      @category = Category.find(params[:id])
    end

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController
  before_action :set_image, only: [:destroy, :show]

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def show
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to admin_images_path
    else
      render :new
    end
  end

  def destroy
    @image.destroy
    redirect_to admin_images_path
  end

  private

    def image_params
      params.require(:image).permit(:image_url, :name)
    end

    def set_image
      @image = Image.find(params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :current_user?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin? if current_user
  end

  def current_user?(user)
    current_user.id == user.id if current_user
  end

  def user_logged_in?
    unless session[:user_id]
      flash[:alert] = "Please Log In"
      redirect_to root_path
    end
  end

  def not_found
    redirect_to root_path
    flash[:alert] = "Uh Oh!! That was not allowed."
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  before_action :user_logged_in?
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def show
  end

  def index
    @categories = Category.all
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end

    def set_category
      @category = Category.find(params[:id])
    end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :correct_user?, only: [:edit, :update, :destroy]
  before_action :user_logged_in?
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def index
    @ideas = current_user.ideas.all
  end

  def show
  end

  def new
    @idea = Idea.new
    @user = User.find(params[:user_id])
  end

  def create
    user = User.find(params[:user_id])
    @idea = user.ideas.new(idea_params)
    @idea.set_images(params[:image])
    if @idea.save
      flash[:success] = "You have created a new idea"
      redirect_to user_idea_path(@idea.user, @idea)
    else
      flash[:alert] = "Something went wrong. Try again!!"
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
  end

  def update
    @idea.images.clear
    @idea.set_images(params[:image])
    @idea.update!(idea_params)
    flash[:success] = "You have updated #{@idea.title}"
    redirect_to user_idea_path(@idea.user)
  end

  def destroy
    @idea.destroy!
    flash[:success] = "You have deleted #{@idea.title}"
    redirect_to user_path(@idea.user)
  end

  private
    def idea_params
      params.require(:idea).permit(:title, :body, :category_id)
    end

    def set_idea
      @idea = Idea.find(params[:id])
    end

    def correct_user?
      redirect_to user_idea_path(@idea) unless current_user?(@idea.user) || current_admin?
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Login Successful. Welcome #{user.username}"
      redirect_to user_path(user)
    else
      flash[:alert] = "Login Failed.\nPlease make sure your email and password are correct."
      render :new
    end
  end

  def destroy
    session.destroy

    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_logged_in?, except: [:new, :create]
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def show
    user = User.find(params[:id])
    unless current_user.id == user.id
      redirect_to root_path
      flash[:notice] = "Sorry, you don't have access to this account!!"
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
      flash[:success] = "You have successfully signed up #{@user.username}"
    else
      render :new
      flash[:alert] = "Sorry. Something went wrong. Please try again and fill out the entire form."
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :username, :password)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/categories/_form.html.haml
= form_for [:admin, @category] do |f|
  %h3
    = f.label :name
    %br/
    = f.text_field :name, class: "name"
  = f.submit class: 'submit'

app/views/admin/categories/edit.html.haml
%h1 Edit #{@category.name}

= render 'form'

app/views/admin/categories/index.html.haml
.admin-create
  = link_to "Create Category", new_admin_category_path, :class => 'new-button'

%h1 All Categories

.categories
  - @categories.each do |category|
    %h3
      = link_to "#{category.name}", admin_category_path(category)

app/views/admin/categories/new.html.haml
%h1 New Category

= render 'form'

app/views/admin/categories/show.html.haml
%div{class: "links"}
  = link_to "Edit Category", edit_admin_category_path(@category), :class => "edit-button"
  = link_to "Delete", admin_category_path(@category), method: :delete, :class => "delete-button"

%h1 #{@category.name}

.category-items
  - @category.ideas.each do |idea|
    %h3
      = link_to "#{idea.title}", user_idea_path(idea.user, idea)

app/views/admin/images/_form.html.haml
= form_for [:admin, @image] do |f|
  %p
    = f.label :name
    %br/
    = f.text_field :name, class: 'name'
  %p
    = f.label :image_url
    %br/
    = f.text_field :image_url, class: 'image-url'
  = f.submit "Add Image", class: 'submit'

app/views/admin/images/index.html.haml
.new-image
  = link_to "Add New Image", new_admin_image_path, :class => "new-button"

%h1 Images

.images
  - @images.each do |image|
    = link_to image_tag(image.image_url), admin_image_path(image)

app/views/admin/images/new.html.haml
%h1 New Image Form

= render 'form'

app/views/admin/images/show.html.haml
.image-show
  %h1 #{@image.name}

  = image_tag @image.image_url

  = link_to "Delete", admin_image_path(@image), method: :delete, :class => "delete-button"

app/views/categories/index.html.haml
%h1 All Categories

.categories
  - @categories.each do |category|
    %h3
      = link_to "#{category.name}", category_path(category)

app/views/categories/show.html.haml
%h1 #{@category.name}

.category-items
  - @category.ideas.each do |idea|
    %h3
      = link_to "#{idea.title}", user_idea_path(idea.user, idea)

app/views/ideas/_form.html.haml
= form_for [@user, @idea] do |f|
  %h3.category-id
    = f.label :category_id
    %br/
    = f.collection_select :category_id, Category.all.order(:name), :id, :name
  %h3.title
    = f.label :title
    %br/
    = f.text_field :title, :class => 'title'
  %h3.body
    = f.label :body
    %br/
    = f.text_area :body
  %h3
    = f.label :images
    %br/
    .images-select
      - Image.all.each do |image|
        %br/
        = check_box_tag "image[]", image.id
        = image_tag image.image_url
  = f.submit class: "submit"

app/views/ideas/edit.html.haml
%h1 Edit #{@idea.title}

= render 'form'

app/views/ideas/index.html.haml
- if current_user
  .new-idea
    = link_to "New Idea", new_user_idea_path(current_user), :class => "new-button"

%h1 Ideas

.ideas
  - @ideas.each do |idea|
    %h3
      = link_to "#{idea.title}", user_idea_path(idea.user, idea)

app/views/ideas/new.html.haml
%h1 Create New Idea

= render 'form'

app/views/ideas/show.html.haml
%h3 Category : #{link_to @idea.category.name, category_path(@idea.category)}

%h1 #{@idea.title}

.idea-images
  - @idea.images.each do |image|
    = image_tag image.image_url

.idea-container
  .idea-box
    %p #{@idea.body}

- if current_user?(@idea.user)
  .idea-links
    %p.links
      = link_to "Edit", edit_user_idea_path(@idea.user, @idea), :class => "edit-button"

      = link_to "Delete", user_idea_path(@idea.user, @idea), method: :delete, :class => "delete-button"

app/views/layouts/_admin_navbar.html.haml
%nav
  %div.home
    = link_to "IdeaBox", root_path
  %div.link
    = link_to "Ideas", ideas_path
  %div.link
    = link_to "Images", admin_images_path
  %div.link
    = link_to "Categories", admin_categories_path
  %div.link
    = link_to "Logout", logout_path, method: :delete
  %div.link
    = link_to "Account", user_path(current_user)

app/views/layouts/_guest_navbar.html.haml
%nav
  %div.home
    = link_to "Ideabox", root_path
  %div.link
    = link_to "Ideas", ideas_path
  %div.link
    = link_to "Categories", categories_path
  %div.link
    = link_to "Sign Up", new_user_path
  %div.link
    = link_to "Log In", login_path

app/views/layouts/_user_navbar.html.haml
%nav
  %div.home
    = link_to "IdeaBox", root_path
  %div.link
    = link_to "Ideas", ideas_path
  %div.link
    = link_to "Categories", categories_path
  %div.link
    = link_to "Logout", logout_path, method: :delete
  %div.link
    = link_to "Account", user_path(current_user)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title IdeaBox
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    - flash.each do |name, msg|
      %div{class: name}
        #{name.upcase} #{name.upcase} #{msg}

    - if current_user && current_user.admin?
      = render 'layouts/admin_navbar'
    - elsif current_user
      = render 'layouts/user_navbar'
    - else
      = render 'layouts/guest_navbar'

    = yield

app/views/users/new.html.haml
%h1 New User Sign Up

= form_for @user do |f|
  %p
    = f.label :username
    %br/
    = f.text_field :username, class: 'username'
  %p
    = f.label :email
    %br/
    = f.email_field :email, class: 'email'
  %p
    = f.label :password
    %br/
    = f.password_field :password, class: 'password'
  = f.submit "Create Account", class: 'submit'

app/views/users/show.html.haml
.new-idea
  = link_to "New Idea", new_user_idea_path(current_user), class: 'new-button'

%h1 Welcome #{current_user.username}

.user-ideas
  - current_user.ideas.each do |idea|
    %h3
      = link_to idea.title, user_idea_path(current_user, idea)